image: registry.gitlab.com/yakan/my-blog:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: app
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - pwd
    - rm public/assets
    - mkdir storage/app/assets
    - ln -s $(pwd)/storage/app/assets public/assets
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit
  only:
    - develop
    - master
deploy_production:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - pwd
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"
  environment:
    name: production
    url: http://aykutyakan.com
  only:
    - master
